services:
  app:
    image: deep-shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npm run seed:data && npm start"]

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s 
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data: